########################### 30/12/2025 ###################
import time
from selenium import webdriver

ch_open = webdriver.ChromeOptions()
ch_open.add_experimental_option('detach', True)

driver = webdriver.Chrome(ch_open)

# driver.get('https://www.swarovski.com/')
# time.sleep(2)
# driver.find_element('xpath','//span[text()="SALE"]').click()
# time.sleep(2)
# driver.find_element('xpath','//span[contains(text(),"New In")]').click()
# time.sleep(2)
# driver.find_element('xpath','//span[contains(text(),"Swarovski Created Diamonds")]').click()
# time.sleep(2)
# driver.find_element('xpath','(//span[contains(text(),"Swarovski Created Diamonds")])[5]').click()
# time.sleep(2)
# driver.close()
#
# driver.get("https://www.python.org/")
# time.sleep(2)
# driver.find_element('xpath','//a[text()="Downloads"]').click()
# time.sleep(2)
# driver.find_element('xpath','//a[text()="Python 3.13.8"]/../..//a[text()="Release notes"]').click()
# time.sleep(2)

driver.get(r"C:\Users\User\PycharmProjects\Selenium_Training\html_files\demo.html")
time.sleep(2)
driver.maximize_window()
time.sleep(2)
driver.find_element('xpath','//td[text()="Python"]/..//input[@name="download"]').click()
time.sleep(2)
driver.find_element('xpath','//td[text()="Java"]/..//input[@name="download"]').click()
time.sleep(2)
driver.find_element('xpath','//label[text()="Apple"]/..//input[@class="alert"]').click()
time.sleep(2)
driver.find_element('xpath','//label[text()="Google"]/..//input[@class="alert"][2]').click()
time.sleep(2)
driver.find_element('xpath','//td[text()="Python"]/..//input[@name="download"]').click()
time.sleep(2)
driver.find_element('xpath','//td[text()="Java"]/..//input[@name="download"]').click()
time.sleep(2)
driver.find_element('xpath','//label[text()="Apple"]/..//input[@class="alert"]').click()
time.sleep(4)
driver.find_element('xpath','//label[text()="Google"]/..//input[@class="alert"][2]').click()
time.sleep(4)
driver.find_element('xpath','//td[text()="Apple"]/..//a[text()="Apple"]').click()
time.sleep(4)
driver.find_element('xpath','//td[text()="Google"]/..//a[contains(text(),"Google")]').click()
time.sleep(4)
driver.find_element('xpath','//td[text()="Windows"]/..//a[contains(text(),"Download")]').click()
time.sleep(4)
driver.find_element('xpath','//td[text()="Android"]/..//a[contains(text(),"Download")]').click()
time.sleep(4)
driver.quit()